name: eduroam CAT (Android) master

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

jobs:
  build:

    runs-on: mreichelt/android:29

    steps:
    - name: Build with Gradle
      run: ./gradlew build
